disable-access-list-simulation = true

# Chain ID for Gnosis Chain
chain-id = 100
tx-gas-limit = "17000000"

[[solver]]
name = "balsolver_gno" # Arbitrary name given to this solver, must be unique
endpoint = "http://0.0.0.0:8080"
absolute-slippage = "5000000000000000000" # Denominated in wei, optional
relative-slippage = "0.05" # Percentage in the [0, 1] range
account = "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6" # The private key of the solver
merge-solutions = true # Multiple solutions proposed by the solver may be combined into one by the driver
response-size-limit-max-bytes = 30000000

[submission]
gas-price-cap = "100000000000" # 100 gwei

[[submission.mempool]]
mempool = "public"
max-additional-tip = "5000000000"
additional-tip-percentage = 0.5

[contracts] # Gnosis Chain contract addresses
gp-v2-settlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
weth = "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d" # WXDAI on Gnosis Chain

[[contracts.cow-amms]]
# address of factory creating new CoW AMMs
factory = "0x703Bd8115E6F21a37BB5Df97f78614ca72Ad7624"
# address of contract to help interfacing with the created CoW AMMs
helper = "0xdB2AeAB529C035469e190310dEf9957ef0398bA8"

[liquidity]
base-tokens = [
    "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d", # WXDAI
    "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1", # WETH
    "0x9C58BAcC331c9aa871AFD802DB6379a98e80CEdb", # GNO
    "0x177127622c4A00F3d409B75571e12cB3c8973d3c", # COW
    "0x6B175474E89094C44Da98b954EedeAC495271d0F", # DAI
    "0x2a22f9c3b484c3629090FeED35F17Ff8F88f76F0", # USDCe
    "0xDDAfbb505ad214D7b80b1f830fcCc89B60fb7A83", # USDC
    "0x4ECaBa5870353805a9F068101A40E0f32ed605C6", # USDT
]

[[order-priority]]
strategy = "external-price"
max-order-age = "5m"

[[order-priority]]
strategy = "creation-timestamp"

[[order-priority]]
strategy = "own-quotes"
max-order-age = "1m"

# Balancer V2 Configuration for Gnosis Chain
[[liquidity.balancer-v2]]
preset = "balancer-v2"
graph-url = "https://api-v3.balancer.fi/"
pool-deny-list = []
reinit-interval = "4h"

# Balancer V3 Configuration for Gnosis Chain
[[liquidity.balancer-v3]]
preset = "balancer-v3"
graph-url = "https://api-v3.balancer.fi/"
pool-deny-list = []
reinit-interval = "4h"

# Uniswap V2 Configuration (optional)
# [[liquidity.uniswap-v2]]
# preset = "uniswap-v2"

# Uniswap V3 Configuration (optional)
# [[liquidity.uniswap-v3]]
# preset = "uniswap-v3"
# graph-url = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
# max_pools_to_initialize = 100
# reinit-interval = "12h"
# graph-api-key = "3d9f2b91a19178e70230ede61bcb0261" 

