# Enable/disable ERC4626 source for this chain
enabled = true

# Fixed list of ERC4626 vault addresses
vaults = [
  "0x773cda0cade2a3d86e6d4e30699d40bb95174ff2",
  "0x7c16f0185a26db0ae7a9377f23bc18ea7ce5d644",
  "0xaf204776c7245bf4147c2612bf6e5972ee483701",
  "0x51350d88c1bd32cc6a79368c9fb70373fb71f375",
  "0x57f664882F762FA37903FC864e2B633D384B411A",
  "0x417bc5b940475203A18C2f320a5ba470D6c5E463",
  "0x58d9AcAC48A4077E4909181c48DEcD00E5ba5DE4",
]