# Enable/disable ERC4626 source for this chain
enabled = true

# Fixed list of ERC4626 vault addresses
vaults = [
  "0xe9F2a5F9f3c846f29066d7fB3564F8E6B6b2D65b",
  "0x616a4E1db48e22028f6bbf20444Cd3b8e3273738",
  "0x7BfA7C4f149E7415b73bdeDfe609237e29CBF34A",
  "0x23479229e52Ab6aaD312D0B03DF9F33B46753B5e",
  "0x5A32099837D89E3a794a44fb131CBbAD41f87a8C",
  "0xe298b938631f750DD409fB18227C4a23dCdaab9b",
  "0x6acD0a165fD70A84b6b50d955ff3628700bAAf4b",
  "0xC768c589647798a6EE01A91FdE98EF2ed046DBD6",
  "0xFA2A03b6f4A65fB1Af64f7d935fDBf78693df9aF",
  "0x0830820D1A9aa1554364752d6D8F55C836871B74",
  "0x5e8B674127B321DC344c078e58BBACc3f3008962",
  "0x74D4D1D440c9679b1013999Bd91507eAa2fff651",
  "0xF8F10f39116716e89498c1c5E94137ADa11b2BC7",
  "0x88b1Cd4b430D95b406E382C3cDBaE54697a0286E",
  "0x729F75Aff28c726e32403e80cef2aFb518CFbfa7",
  "0x9272d6153133175175bc276512b2336be3931ce9",
  "0x589A7339C6d0c8777E7429F57f2f95c069c37288",
  "0x98eFe85735F253a0ed0Be8e2915ff39f9e4AfF0F",
]