# Chain ID for Avalanche
chain-id = 43114
tx-gas-limit = "8000000"

[[solver]]
name = "balancer-solver-avalanche" # Arbitrary name given to this solver, must be unique
endpoint = "http://0.0.0.0:8085"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.1" # Percentage in the [0, 1] range
account = "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6" # The private key of the solver
merge-solutions = true # Multiple solutions proposed by the solver may be combined into one by the driver
response-size-limit-max-bytes = 30000000

[submission]
gas-price-cap = "1000000000000"

[[submission.mempool]]
mempool = "public"
max-additional-tip = "5000000000"
additional-tip-percentage = 0.05

[contracts] # Avalanche contract addresses
gp-v2-settlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
weth = "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7" # WAVAX on Avalanche

[[contracts.cow-amms]]
# address of factory creating new CoW AMMs
factory = "0x86f3df416979136cb4fdea2c0886301b911c163b"
# address of contract to help interfacing with the created CoW AMMs
helper = "0x86f3df416979136cb4fdea2c0886301b911c163b"

[liquidity]
base-tokens = [
    "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7", # WAVAX
    "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70", # DAI
    "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E", # USDC
    "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7", # USDT
    "0xcb8b5CD20BdCaea9a010aC1F8d835824F5C87A04", # COW
]

[[order-priority]]
strategy = "external-price"
max-order-age = "5m"

[[order-priority]]
strategy = "creation-timestamp"

[[order-priority]]
strategy = "own-quotes"
max-order-age = "1m"

# Balancer V2 Configuration for Avalanche
[[liquidity.balancer-v2]]
preset = "balancer-v2"
graph-url = "https://api-v3.balancer.fi/"
pool-deny-list = []
reinit-interval = "12h"

# Balancer V3 Configuration for Avalanche
[[liquidity.balancer-v3]]
preset = "balancer-v3"
graph-url = "https://api-v3.balancer.fi/"
pool-deny-list = []
reinit-interval = "12h"

# Uniswap V2 Configuration (optional)
# [[liquidity.uniswap-v2]]
# preset = "uniswap-v2"

# Uniswap V3 Configuration (optional)
# [[liquidity.uniswap-v3]]
# preset = "uniswap-v3"
# graph-url = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
# max_pools_to_initialize = 100
# reinit-interval = "12h"

 