# Enable/disable ERC4626 source for this chain
enabled = true

# Fixed list of ERC4626 vault addresses
vaults = [
  "0xd7da0de6ef4f51d6206bf2a35fcd2030f54c3f7b",
  "0x2d324fd1ca86d90f61b0965d2db2f86d22ea4b74",
  "0xe1bFC96d95BAdCB10Ff013Cb0C9C6c737ca07009",
  "0x59933c571d200dc6A7Fd1CDa22495dB442082E34",
  "0x7D0394F8898fBA73836Bf12bD606228887705895",
  "0xdFD2b2437a94108323045C282fF1916de5Ac6Af7",
  "0x45cf39EeB437FA95Bb9b52c0105254a6BD25D01e",
  "0xC38aD3527A4B821BF437639cBA8Bf567BFa63A13",
  "0x61933AF56431280EE4e5667133D8aF6322D64B32",
  "0x7883978D1F322641a3AaA82Bac3b0a6Dee7A171E",
  "0x3929336Afd0BBa6FCAbB67dFB78610379C66B43B",
  "0x79459f4C9AfC902488109D058C3E76ed0B037c41",
  "0x39dE0f00189306062D79eDEC6DcA5bb6bFd108f9",
  "0xa446938b0204Aa4055cdFEd68Ddf0E0d1BAB3E9E",
  "0x2137568666f12fc5A026f5430Ae7194F1C1362aB",
  "0x5030183B3DD0105d69D7d45595C120Fc4b542EC3",
  "0x72F92a966f1874f74e1b601BEe7CF57031B53A03",
  "0x51b47B3013863c52CA28D603De3C2d7a5FEf50B9",
]