# Enable/disable ERC4626 source for this chain
enabled = true

# Fixed list of ERC4626 vault addresses
vaults = [
  "0xF7DE3c70F2db39a188A81052d2f3C8e3e217822a",
  "0x2371e134e3455e0593363cBF89d3b6cf53740618",
  "0xBEEF01735c132Ada46AA9aA4c54623cAA92A64CB",
  "0xbEef047a543E45807105E51A8BBEFCc5950fcfBa",
  "0xbEEFC01767ed5086f35deCb6C00e6C12bc7476C1",
  "0xD4fa2D31b7968E448877f69A96DE69f5de8cD23E",
  "0x0bfc9d54Fc184518A81162F8fB99c2eACa081202",
  "0x7Bc3485026Ac48b6cf9BaF0A377477Fff5703Af8",
  "0x0FE906e030a44eF24CA8c7dC7B7c53A6C4F00ce9",
  "0x775F661b0bD1739349b9A2A3EF60be277c5d2D29",
  "0x5F9D59db355b4A60501544637b00e94082cA575b",
  "0xC71Ea051a5F82c67ADcF634c36FFE6334793D24C",
  "0xbEeFc011e94f43b8B7b455eBaB290C7Ab4E216f1",
  "0x7204B7Dbf9412567835633B6F00C3Edc3a8D6330",
  "0x1e6ffa4e9F63d10B8820A3ab52566Af881Dab53c",
  "0x701907283a57FF77E255C3f1aAD790466B8CE4ef",
  "0xb51EDdDD8c47856D81C8681EA71404Cec93E92c6",
  "0xA1b60d96e5C50dA627095B9381dc5a46AF1a9a42",
  "0x30881Baa943777f92DC934d53D3bFdF33382cab3",
  "0x097FFEDb80d4b2Ca6105a07a4D90eB739C45A666",
  "0x90551c1795392094FE6D29B758EcCD233cFAa260",
  "0x2411802D8BEA09be0aF8fD8D08314a63e706b29C",
  "0x1202F5C7b4B9E47a1A484E8B270be34dbbC75055",
  "0x6A1792a91C08e9f0bFe7a990871B786643237f0F",
  "0xDBDC1Ef57537E34680B898E1FEBD3D68c7389bCB",
  "0xBEeF1f5Bd88285E5B239B6AAcb991d38ccA23Ac9",
]