# Enable/disable ERC4626 source for this chain
enabled = true

# Fixed list of ERC4626 vault addresses
vaults = [
  "0x4cE13a79f45C1Be00BdABD38B764aC28C082704E",
  "0xD9E3Ef2c12de90E3b03F7b7E3964956a71920d40",
  "0x52Dc1FEeFA4f9a99221F93D79da46Ae89b8c0967",
  "0x7F6501d3B98eE91f9b9535E4b0ac710Fb0f9e0bc",
  "0xe98fc055c99DECD8Da0c111B090885d5d15C774E",
  "0xa6D12574eFB239FC1D2099732bd8b5dC6306897F",
  "0xEAB84053B99f2ec4433F5121A1CB1524c8c998F8",
  "0xf09EDbF2655B2A56753bD60D22CeAB2AC5D04188",
  "0xbB8A61425DFE172AA3a6f882aAFaBA00B32b7d59",
  "0xf253BD61aEd0E9D62523eA76CD6F38B4a51dA145",
  "0xE6D5923281c89DC989D00817387292387552d5C1",
  "0xD089B4cb88Dacf4e27be869A00e9f7e2E3C18193",
  "0x4ff50C17df0D1b788d021ACd85039810a1aA68A1",
  "0x45Df0656F8aDf017590009d2f1898eeca4F0a205",
]